INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (1,"Bulzi",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (2,"Harrison Hot Springs",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (3,"Okara",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (4,"Salamanca",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (5,"Lachine",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (6,"Dibrugarh",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (7,"Francavilla Fontana",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (8,"Sulzano",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (9,"Çermik",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (10,"Birori",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (11,"Vorselaar",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (12,"Ragnies",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (13,"Smetlede",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (14,"Goderich",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (15,"Rutigliano",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (16,"Orvieto",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (17,"Kailua",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (18,"Calera de Tango",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (19,"Spaniard's Bay",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (20,"Olmué",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (21,"La Florida",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (22,"Archennes",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (23,"Tsiigehtchic",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (24,"Port Hope",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (25,"Porto Alegre",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (27,"Florida",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (28,"Rea",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (29,"Oyen",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (30,"Missoula",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (31,"Alnwick",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (32,"Herstappe",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (33,"Monte San Giovanni in Sabina",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (34,"Urbe",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (35,"Pointe-du-Lac",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (36,"Port Moody",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (37,"Cumberland",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (38,"Liberia",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (39,"Rio Marina",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (40,"Deline",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (41,"Saint-Nazaire",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (42,"Bath",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (44,"Friedberg",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (45,"Masone",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (46,"Bahraich",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (47,"Van",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (48,"Leiden",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (49,"Termini Imerese",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (50,"Marseille",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (51,"Harbour Grace",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (52,"Kohima",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (53,"Gelbressee",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (54,"McCallum",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (55,"Waterbury",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (56,"Feltre",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (57,"Rechnitz",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (58,"Orléans",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (59,"Vance",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (60,"Osasco",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (61,"Khandwa",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (62,"Montgomery",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (63,"Anderlues",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (64,"Banff",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (65,"Allahabad",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (66,"Marcinelle",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (67,"Mangalore",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (68,"Hattiesburg",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (69,"Maringá",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (70,"Katowice",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (71,"Wetaskiwin",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (72,"Giardinello",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (73,"Gavirate",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (74,"Sunset Point",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (75,"Mobile",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (76,"Mandasor",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (77,"Grand Rapids",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (78,"Crowsnest Pass",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (79,"Honolulu",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (80,"Cabildo",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (81,"Patna",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (82,"Caprauna",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (83,"Lo Prado",14,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (84,"Annapolis",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (85,"Lille",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (86,"Tufo",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (87,"Bossire",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (88,"Isnes",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (89,"Petorca",16,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (90,"Wolfurt",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (91,"Cambridge",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (92,"Dresden",12,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (93,"Tollembeek",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (94,"Marzabotto",13,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (95,"Orilla",17,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (96,"Nizip",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (97,"Brampton",11,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (98,"Salvador",15,"1");
INSERT INTO `tb_cidade` (`id`,`nome`,`estado`,`version`) VALUES (100,"Altavilla Irpina",13,"1");